minecraft:
  loader: "Fabric"
  version: "1.20.4"
  remove-alpha: false
  accepted:
    - "1.20.3"
    - "1.20.2"
    - "1.20.1"
    - "1.20"

overrides:
  use-modpack-overrides: true
  edit-overrides-options: true

build:
  curseforge-modpack-zip: false
  modrinth-modpack-zip: true
  classic-zip-folder: false

modpack:
  name: "Fabulously Optimized ++ $VERSION"
  version: "1.0.0"
  author: "LyFlow"
  summary: "Improve your graphic and performance"
